### PR TITLE
Use parameter value for login URL in exec_anon.xml

### PR DESCRIPTION
**Pull request by lydonb**
Fixes issue where Execute Anonymous against a sandbox fails due to URL being hard-coded to login.salesforce.com.

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks, for this, though i'm puzzled how using ${host} works, its referenced in the login macro before it's initialised?

**Comment by lydonb** [comment]
Yeah, I'm honestly not sure either (I don't have a lot of experience with ant), but I tested it out and it works.

Thinking about it now, maybe it's because when I make the ant call I always pass it the -Dsf.serverurl=xyz.salesforce.com parameter for the instance where my org is running?

**Comment by lydonb** [comment]
If you have another suggestion I'm happy to make the change. I just noticed that this was logged as a bug last week after I submitted this pull.

**Comment by afawcett** [comment]
Hi @lydonb i started to try to test this at the weekend, but all my test sandbox logins failed, sorry should have updated that i was attempting to test. I'm still puzzled about the ${host} reference is all. 

What i think is needed is a new attribute like the standard SF Ant tasks to pass the serverUrl

    <executeAnon userName="username" password="password" serverUrl="https://test.salesforce.com>

Then internally when it calls <logon> pass it, not that we still need the instanceUrl back (which i think should be renamed to instanceUrl to avoid confusion).

    <login username="@{username}" password="@{password}" serverurl="@{serverUrl}" instanceurl="instanceUrl" sessionId="sessionId"/>

Something like this anyway, make sense?

See issue [11](https://github.com/financialforcedev/df12-deployment-tools/issues/11) for more chat.

**Comment by lydonb** [comment]
@afawcett I just tested it out on a clean fork. I updated the build.properties file with username & password, and changed the sf.server property to https://test.salesforce.com. 

Then I changed line 110 in exec_anon.xml to this:
`<http url="${sf.server}/services/Soap/c/30.0" method="POST" failonunexpected="false" entityProperty="loginResponse" statusProperty="loginResponseStatus">`

Then I called `ant LoadBasicDataset` to test it out and it worked.

Do you see any issues with this approach?

**Comment by afawcett** [comment]
Nope, that sounds spot on! :+1:

**Comment by afawcett** [comment]
Though probably want to default sf.server for backwards compatibility sake.

**Comment by lydonb** [comment]
@afawcett, isn't sf.server defaulted in the build.properties file? Or are you saying add an attribute to the Login macro with a default value of "http://www.salesforce.com", and pass it with the value ${sf.server} on line 59? I'm just not sure where to set that default server value.

**Pull request closed without merging**
